navikt/kabal-api

deploy/nais.yaml, src/main/kotlin/no/nav/klage/oppgave/config/AxsysClientConfiguration.kt
ApiKey'en leses inn fra en secret i kubernetes. Secreten er lagt til i både dev og prod.
=> Lagt til støtte for apikey mot apigw for axsys

src/main/kotlin/no/nav/klage/oppgave/clients/PdlClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/pdl/HentPersonRequest.kt, src/main/kotlin/no/nav/klage/oppgave/domain/pdl/HentPersonResponse.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt, src/main/resources/pdl/hentPerson.graphql, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveServiceTest.kt
=> Bulk fetch from PDL

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/api/FeatureToggleController.kt, src/main/kotlin/no/nav/klage/oppgave/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/ByProfileStrategy.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/TokenUtils.kt, src/main/resources/application.yml
Jeg er ingen Unleash-ekspert, så takknemlig for alle kommenterer! :) 
TokenUtils er kopiert fra OppgaveService. Det var forholdsvis omfattende greier for å hente ut Identen til en saksbehandler, kanskje @oyvind-wedoe kan si noe om det er riktig å gjøre det sånn i denne konteksten?  Hvis det er korrekt, så kan jeg refaktorere litt så OppgaveService og Unleash bruker samme kode istedet for å copy-paste..
=> Lagt til støtte for feature toggling med unleash

deploy/dev.yaml, src/main/kotlin/no/nav/klage/oppgave/api/FeatureToggleController.kt, src/main/kotlin/no/nav/klage/oppgave/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/ByEnhetStrategy.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/ByProfileStrategy.kt, src/main/resources/application.yml
Har lagt til et Unprotected-endepunkt, for å kunne teste og/eller bruke featuretoggles uten autentisering, hvis det er aktuelt.
Har lagt til en ny strategi - ByEnhet, for å kunne slippe inn ett og ett kontor.
=> Utvide feature toggling

src/main/kotlin/no/nav/klage/oppgave/api/OppgaveController.kt, src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/gosys/Oppgave.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveServiceTest.kt
Eller sette tilfeldig hjemmel på alle oppgaver.. Ment som midlertidig kode.. :) 
Spent på tilbakemeldingene på endepunktet for setHjemmel. Jeg er ingen patch-fan selv, dette er måten jeg foretrekker å gjøre ting på.. :)
=> Lagt til mulighet for å sette hjemmel på en oppgave

src/main/kotlin/no/nav/klage/oppgave/config/AxsysClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/MicrosoftGraphClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/Norg2ClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/OppgaveClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/PdlClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/StsClientConfiguration.kt
..for å bli kvitt prematurely closed problemer
=> Forsøker å disable connection pooling i WebClient 

src/main/kotlin/no/nav/klage/oppgave/api/OppgaveController.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt
..ikke bare string. Fikset mapping av saksbehandlere i returen
=> Endret input for assign saksbehandler til å være json

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/clients/AxsysClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/MicrosoftGraphClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/Norg2Client.kt, src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/PdlClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/StsClient.kt, src/main/kotlin/no/nav/klage/oppgave/config/RetryConfig.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/OppgaveRepository.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/SaksbehandlerRepository.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/ByEnhetStrategy.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/TokenUtils.kt, src/test/kotlin/no/nav/klage/oppgave/clients/OppgaveClientTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveServiceTest.kt
Har lagt inn Spring Retry biblioteket, samt tatt i bruk Retryable i klientene våre.
Jeg sliter litt med å se hvordan jeg skal få lagt en retry på det kallet som feiler av og til:
```
Error starting Tomcat context
could not retrieve metadata from url: https://login.microsoftonline.com/966ac572-f5b7-4bbe-aa88-c76419c0f851/v2.0/.well-known/openid-configuration. received exception java.net.ConnectException: Connection refused (Connection refused)
```
Det er et kall som gjøres av et bibliotek, ikke av oss.. Men... Det er jo et NAV-bibliotek, så kanskje vi kan få ordnet en PR på det som gjør det mulig for oss?
=> Lagt til Spring Retry

src/main/kotlin/no/nav/klage/oppgave/api/FeatureToggleController.kt, src/main/kotlin/no/nav/klage/oppgave/api/OppgaveController.kt, src/main/kotlin/no/nav/klage/oppgave/domain/gosys/Oppgave.kt, src/main/kotlin/no/nav/klage/oppgave/domain/view/OppgaveView.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/OppgaveRepository.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt, src/main/kotlin/no/nav/klage/oppgave/service/unleash/ByEnhetStrategy.kt
Beklager, men det er noen formatterings-endringer i PRen..
Endringene i REST-APIet er ikke bakoverkompatible.
Det mangler tester. Det er et generelt problem, og egentlig det jeg jobber med. Hvis det er ønskelig å få denne ut før det er på plass, så kan den merges inn. Eller så kan vi vente til jeg har ordnet det. :)
=> Optimistic locking hele veien

src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt
.. så vi ikke skal fly i blinde når det feiler
=> Lagt til logging av WebClientResponseExceptions mot Oppgave,

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/api/FeatureToggleController.kt, src/main/kotlin/no/nav/klage/oppgave/config/CustomTraceFilter.kt, src/test/kotlin/no/nav/klage/oppgave/api/FeatureToggleControllerTest.kt
Autentisering fungerer ikke ennå.
=> Lagt til en første controller-test. 

src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/OppgaverSearchCriteria.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt
Lagt til flere filtermuligheter i OppgaveSearchCriteria og OppgaveClient, samt laget noen predefinerte spørringer for å få antall til bruk i statistikk
=> Statistikk-spørringer

deploy/dev.yaml, deploy/nais.yaml, src/main/kotlin/no/nav/klage/oppgave/api/OppgaveController.kt, src/main/kotlin/no/nav/klage/oppgave/clients/AxsysClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/KlageProxyClient.kt, src/main/kotlin/no/nav/klage/oppgave/config/KlageProxyClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/domain/Tilganger.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/EnhetRepository.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/InnloggetSaksbehandlerRepository.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/SaksbehandlerRepository.kt, src/main/resources/application.yml
Mangler litt fremdeles, men tar gjerne i mot feedback på om jeg er på rett spor. Finnes det noen enklere måte å hente ut lederen i en enhet på?
=> Laget litt kode rundt det å hente roller og å hente ansatte i enhet

src/main/kotlin/no/nav/klage/oppgave/api/FeatureToggleInterceptor.kt, src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt, src/main/kotlin/no/nav/klage/oppgave/config/FeatureToggleConfig.kt, src/main/kotlin/no/nav/klage/oppgave/config/FeatureToggleInterceptor.kt, src/main/kotlin/no/nav/klage/oppgave/config/problem/ProblemHandlingControllerAdvice.kt, src/main/kotlin/no/nav/klage/oppgave/exceptions/OppgaveExceptions.kt, src/main/kotlin/no/nav/klage/oppgave/service/TokenService.kt, src/test/kotlin/no/nav/klage/oppgave/clients/OppgaveClientTest.kt
Lagt til en HandlerInterceptor for å featuretoggle alle endepunkt i OppgaveController. Returnerer 403 hvis ikke enabled.
=> Featuretoggler OppgaveController

src/main/kotlin/no/nav/klage/oppgave/api/OppgaveController.kt, src/main/kotlin/no/nav/klage/oppgave/domain/OppgaverSearchCriteria.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveMapper.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveStatistikkService.kt, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveServiceTest.kt
Derfor har jeg dratt ut statistikk i egen service, dratt ut mapping i egen service, samt lagt inn igjen getOppgave. Håper det smaker! :) 
Har planer om å gjøre mer, men tar det litt stegvis..
=> OppgaveService var blitt for stor..

deploy/nais.yaml
Vilt, men dette skal være alt....
=> Config for Postgres12

src/main/kotlin/no/nav/klage/oppgave/config/OppgaveKopiRepositoryConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/Ident.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/IdentType.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/MetadataNoekkel.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/OppgaveKopi.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/Prioritet.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/Status.kt, src/main/kotlin/no/nav/klage/oppgave/domain/oppgavekopi/Statuskategori.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/OppgaveKopiRepository.kt, src/test/kotlin/no/nav/klage/oppgave/db/FlywayMigrationTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/OppgaveKopiRepositoryTest.kt
Lagt til OppgaveKopi domeneobjekt med tilhørende klasser, samt et Repository for å lagre dette i db
=> Lagt til OppgaveKopi domeneklasse, samt Repository for å lagre til db ved mottak fra Oppgave

src/main/kotlin/no/nav/klage/oppgave/config/CacheInvalidationConfiguration.kt
så vi ikke skal få problemer med seraliseringsfeil...
=> Invaliderer alle cachene ved oppstart

src/main/kotlin/no/nav/klage/oppgave/config/OppgaveClientConfiguration.kt, src/main/resources/logback-spring.xml, src/test/kotlin/no/nav/klage/oppgave/clients/OppgaveJsonMappingTest.kt
så vi kan se om vi får med identer
=> Lagt til logging av oppgave-responser til securelogs, 

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/config/KafkaConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/egenansatt/EgenAnsatt.kt, src/main/kotlin/no/nav/klage/oppgave/egenansatt/EgenAnsattHealthIndicator.kt, src/main/kotlin/no/nav/klage/oppgave/egenansatt/EgenAnsattKafkaConsumer.kt, src/main/kotlin/no/nav/klage/oppgave/egenansatt/EgenAnsattService.kt, src/main/resources/application-dev-gcp.yml, src/main/resources/application-prod-gcp.yml, src/main/resources/application.yml, src/test/kotlin/no/nav/klage/oppgave/egenansatt/EgenAnsattKafkaConsumerTest.kt
som den leser fra en Kafka-topic.. :-)
=> Lagt til en service som cacher egenAnsatt-verdier, 

src/main/kotlin/no/nav/klage/oppgave/api/SaksbehandlerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/OppgaveMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/OppgaverQueryParamsMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/Enhet.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/OppgaveView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/OppgaverQueryParams.kt, src/main/kotlin/no/nav/klage/oppgave/clients/gosys/Oppgave.kt, src/main/kotlin/no/nav/klage/oppgave/clients/gosys/OppgaveClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/OppgaverSearchCriteria.kt, src/main/kotlin/no/nav/klage/oppgave/domain/SaksbehandlerDomene.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/InnloggetSaksbehandlerRepository.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/SaksbehandlerRepository.kt, src/main/kotlin/no/nav/klage/oppgave/service/OppgaveStatistikkService.kt, src/main/kotlin/no/nav/klage/oppgave/service/SaksbehandlerService.kt, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveFacadeTest.kt
Dette endrer ikke metode-kallet, så det er mulig dere vil utvide den til å gjøre det også.
=> Endre ytelse til tema

build.gradle.kts, deploy/dev.yaml, deploy/nais.yaml, src/main/kotlin/no/nav/klage/oppgave/api/OppgaveFacade.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/OppgaveMapper.kt, src/main/kotlin/no/nav/klage/oppgave/clients/pdl/PdlFacade.kt, src/main/kotlin/no/nav/klage/oppgave/clients/pdl/graphql/HentPersonMapper.kt, src/main/kotlin/no/nav/klage/oppgave/config/ElasticsearchConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/ElasticsearchServiceConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/EsOppgave.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/Prioritet.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/Status.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/Statuskategori.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/ElasticsearchRepository.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/InnloggetSaksbehandlerRepository.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/SaksbehandlerRepository.kt, src/main/resources/application-dev-gcp.yml, src/main/resources/application.yml, src/main/resources/elasticsearch/mapping.json, src/main/resources/elasticsearch/settings.json, src/main/resources/logback-spring.xml, src/test/kotlin/no/nav/klage/oppgave/service/CreateIndexFromEsOppgaveTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/ElasticsearchIndexingTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/ElasticsearchRepositoryTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveFacadeTest.kt
Indexering av Oppgave når vi mottar lokale kopier og søk i elastic som alternativ til søk i Oppgave-systemet
(Har ikke opprettet secretene ennå, tar det når PRen evt er godkjent og før det merges.)
=> Lagt til elasticsearch-oppsett

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphClient.kt, src/main/kotlin/no/nav/klage/oppgave/config/CustomTraceFilter.kt, src/main/kotlin/no/nav/klage/oppgave/config/FeatureToggleInterceptor.kt, src/main/kotlin/no/nav/klage/oppgave/config/SaksbehandlerRolleInterceptor.kt, src/test/kotlin/no/nav/klage/oppgave/db/FlywayMigrationTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/OppgaveKopiRepositoryTest.kt
Har oppdatert Spring Boot til siste versjon, og en rekke andre dependencies også. (Noen av dem måtte oppdateres for å henge med spring boot, f.eks spring mockk, men generelt har jeg bare funnet siste versjon ut fra et prinsipp om at det er fint å være oppdatert..)
=> Oppdaterer dependencies

build.gradle.kts
Bygget kjørte fint uten, så virker ikke som om den var i bruk heller?
=> Napper bort dependency som er gammel og ikke skal brukes. 

src/main/kotlin/no/nav/klage/oppgave/clients/pdl/PdlFacade.kt, src/main/kotlin/no/nav/klage/oppgave/clients/pdl/graphql/HentPersonerResponse.kt, src/test/kotlin/no/nav/klage/oppgave/clients/PdlClientTest.kt
Fikset feil i pdl-typene og lagt til PdlClientTest for å teste oppførsel med empty arrays i json og generell mapping
=> Json empty array

src/main/resources/logback-spring.xml
som ikke egentlig er reelle og vi ikke får gjort noe med..
=> Skrur av warnings form Custom Conversions i ES

src/main/kotlin/no/nav/klage/oppgave/clients/saf/graphql/HentDokumentoversiktBrukerRequest.kt, src/main/kotlin/no/nav/klage/oppgave/clients/saf/graphql/HentJournalpostRequest.kt, src/main/kotlin/no/nav/klage/oppgave/clients/saf/graphql/SafGraphQlClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/saf/graphql/SafResponse.kt, src/main/kotlin/no/nav/klage/oppgave/service/DokumentService.kt, src/main/resources/saf/hentJournalpost.graphql, src/test/kotlin/no/nav/klage/oppgave/clients/SafDokumentoversiktBrukerTest.kt, src/test/kotlin/no/nav/klage/oppgave/clients/SafJournalpostTest.kt
samt lagt til bedre feilhåndtering og testing av denne
=> Lagt til en ny metode mot Saf for hentJournalpost, 

src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
D.v.s. avsluttet (dato) er ikke satt til noe.
=> Finn mottak med pågående klagebehandlinger. 

src/main/kotlin/no/nav/klage/oppgave/service/OverfoeringsdataParserService.kt, src/test/kotlin/no/nav/klage/oppgave/service/OverfoeringParserTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/OverfoeringsdataParserServiceTest.kt
Det vi vel først og fremst er ute etter er mottattDato, men kan også hente ut fraEnhet, tilEnhet, og hvem som gjorde endringen (saksbehandler)
=> Testet og funnet en metode for å parse div informasjon ut av beskrivelse

src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingView.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/EsKlagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Mottak.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/resources/db/migration/V3__Create_klage_schema.sql, src/test/kotlin/no/nav/klage/oppgave/service/OppgaveKopiServiceTest.kt
..og opprettelse av Mottak og Klagebehandling, tatt i bruk OverfoeringsdataParserServicen som henter ut data fra beskrivelsen i oppgaven.
=> Endret på logikken i mottak av Oppgaver 

src/main/kotlin/no/nav/klage/oppgave/clients/axsys/Tilganger.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/SaksbehandlerRepository.kt, src/main/resources/application-dev-gcp.yml, src/main/resources/application-prod-gcp.yml
Gjør at vi bør slippe GOS-feilen i loggene..
Dette spørsmålet må avklares før dette merges: https://nav-it.slack.com/archives/CA0AX0Y2V/p1614785221000800
Swagger for v2: https://axsys.dev.adeo.no/swagger-ui/?urls.primaryName=API%20versjon%202
Swagger for v1: https://axsys.dev.adeo.no/swagger-ui/?urls.primaryName=API%20versjon%201
=> Endret til v2 av Axsys, hvor man har endret fagomrader til temaer. 

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingListController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/KvalitetsvurderingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/facade/KlagebehandlingFacade.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KvalitetsvurderingInput.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Endringslogginnslag.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/KlagebehandlingAggregatFunctions.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Kvalitetsvurdering.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/ConnectOppgaveToMottakEventListener.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/IndexKlagebehandlingEventListener.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StoreEndringsloggEventListener.kt, src/main/kotlin/no/nav/klage/oppgave/events/KlagebehandlingEndretEvent.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/EndringsloggRepository.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/resources/db/migration/V3__Create_klage_schema.sql
Deler opp kvalitetsvurderings-operasjonene i mindre biter. Innfører Endringslogg for logge hvem som har gjort hva når i en klagebehandling. Denne commiten dekker ikke alt, men er ment å vise tankegangen. 
(Har bare fullført Grunn, og har ikke laget database-skjema..)
=> Endringslogg

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingDetaljerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/KvalitetsvurderingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt
som er en merge av KlagebehandlingController og KvalitetsvurderingController, med et View-objekt som inneholder alle dataene. De andre kan slettes senere.
=> Lagt til KlagebehandlingDetaljerController, 

src/main/resources/application.yml
=> Bruker certs mot AAD i stedet for brukernavn/passord. 

src/main/kotlin/no/nav/klage/oppgave/api/controller/DokumentController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingDetaljerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingListController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/KvalitetsvurderingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingInput.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingListView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KvalitetsvurderingInput.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KvalitetsvurderingView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/Saksbehandlertildeling.kt, src/main/kotlin/no/nav/klage/oppgave/config/problem/ProblemHandlingControllerAdvice.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/exceptions/OppgaveExceptions.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/KlagebehandlingRepository.kt, src/main/kotlin/no/nav/klage/oppgave/service/DokumentService.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
Hiver 409 Conflict hvis versjonsnummeret gui sender inn ikke matcher det som finnes i db.
=> Forsøk på optimistic locking hele veien ut i gui

src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/RelatedKlagebehandlinger.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/ElasticsearchRepository.kt, src/test/kotlin/no/nav/klage/oppgave/service/RelatedKlagebehandlingerTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/StatistikkInElasticsearchRepositoryTest.kt
basert på fnr, saksreferanse og journalpostid. Ikke laget noe Rest-endepunkt, vet ikke helt hvordan det skal se ut
=> Laget ES-spørringer for å finne relaterte klagebehandlinger, 

build.gradle.kts, src/main/resources/db/migration/V5__Give_access_to_schemas.sql, src/test/kotlin/no/nav/klage/oppgave/db/FlywayMigrationTest.kt, src/test/kotlin/no/nav/klage/oppgave/db/TestPostgresqlContainer.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/KlagebehandlingRepositoryTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/MottakRepositoryTest.kt, src/test/resources/application-local.yml
Fjernet H2 og tar i bruk Postgres (i Docker) i testene våre.
=> Lagt til flyway migrering som skal gi select rettigheter til våre personlige brukere

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingVedtakController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/VedtakInput.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/VedtakView.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/KlagebehandlingAggregatFunctions.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Vedtak.kt, src/main/kotlin/no/nav/klage/oppgave/exceptions/OppgaveExceptions.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/kotlin/no/nav/klage/oppgave/service/VedtakService.kt, src/main/resources/db/migration/V2__Expand_vedtak.sql
Lagt til støtte for oppdatering av Utfall-feltet i Vedtak, venter på tilbakemelding fra team før jeg legger inn endepunkter for resten.
=> Lager Vedtak når ny Klagebehandling opprettes. 

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/OversendtKlage.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/KlagebehandlingAggregatFunctions.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Mottak.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/resources/db/migration/V3__Add_kommentar.sql
I OversendtKlage, Mottak, Klagebehandling og KlagebehandlingDetaljerView
=> Lagt til kommentar-felt 

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/EsKlagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/EsSaksdokument.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/EsVedtak.kt, src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt, src/main/resources/elasticsearch/mapping.json, src/test/kotlin/no/nav/klage/oppgave/service/ElasticsearchIndexingTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/ElasticsearchServiceTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/RelatedKlagebehandlingerTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/StatistikkInElasticsearchServiceTest.kt
Es-modellen matcher nå i stor grad domenemodellen, og tanken er at den nå kan brukes til statistikk-spørringer og annet i enda større grad enn før.
=> Utvidet ES-modellen med EsSaksdokument og EsVedtak, samt en rekke felter i EsKlagebehandling

src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingInput.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KvalitetsvurderingInput.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/Saksbehandlertildeling.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/VedtakInput.kt, src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Hjemmel.kt
Lagt til at MANGLER skal være mulig å velge som hjemmel for Tema OMS
Gjort klagebehandlingVersjon obligatorisk i Input-klassene
=> Smaa endringer

src/main/kotlin/no/nav/klage/oppgave/config/MetricsConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Fagsystem.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/kotlin/no/nav/klage/oppgave/service/MottakService.kt
Lagt til en counter for mottatte klager. Ruter alle funksjonelle metrics til influx, alle andre (tekniske) til prometheus.
Fikset byggefeil fra main
=> different strokes for different folks

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingerQueryParamsMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingerQueryParams.kt, src/main/kotlin/no/nav/klage/oppgave/clients/gosys/OppgaveClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt
Co-authored-by: Hågen Hasle <hagen.hasle@nav.no>
=> Lagt til støtte for å vise frem ferdigstilte oppgaver

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingListController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingListView.kt
men fyller de bare når ferdigstiltFom er brukt. Droppet å lage en ny projeksjon, syntes dette var mer DRY
=> Lagt til flere felter i KlagebehandlingListView, 

src/main/kotlin/no/nav/klage/oppgave/api/controller/MockDataController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KodeverkResponse.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/OversendtKlage.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/VedtakView.kt, src/main/kotlin/no/nav/klage/oppgave/clients/joark/JoarkClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/BrevMottaker.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klager.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Mottak.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/PartId.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Prosessfullmektig.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/SakenGjelder.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Vedtak.kt, src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/PartIdType.kt, src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Rolle.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHService.kt, src/main/kotlin/no/nav/klage/oppgave/service/MottakService.kt, src/main/resources/db/migration/V1__Create_klage_schema.sql, src/test/kotlin/no/nav/klage/oppgave/db/FlywayMigrationTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/KlagebehandlingRepositoryTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/MottakRepositoryTest.kt
og gjort om noen enums til kodeverk-enums
=> Gjort om en del entities som var oneToOne til å være embeddables, 

src/main/kotlin/no/nav/klage/oppgave/api/controller/SaksbehandlerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/Medunderskriver.kt, src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphResponse.kt, src/main/kotlin/no/nav/klage/oppgave/config/CacheWithJCacheConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/repositories/SaksbehandlerRepository.kt, src/main/kotlin/no/nav/klage/oppgave/service/SaksbehandlerService.kt
for en saksbehandler for et gitt tema
=> legger til endepunkt for å returnere medunderskrivere 

src/main/kotlin/no/nav/klage/oppgave/config/FunksjonelleGaugesConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt
Ikke implementert ES-spørringene, det vil jeg at noen andre skal få gjøre.
Jeg er også usikker på hvordan jeg bruker tags sammen med en supplier, her trenger jeg litt input.
=> Lagt til gauges for det Nora ønsker å vise i Grafana.

src/main/kotlin/no/nav/klage/oppgave/api/mapper/EsKlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/service/IndexService.kt
Så en del tar seg av View-objektene, det andre av mappingen til Es
=> Deler KlagebehandlingMapper i to

src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt, src/main/kotlin/no/nav/klage/oppgave/util/StatsUtils.kt, src/test/kotlin/no/nav/klage/oppgave/util/StatsUtilsTest.kt
Også lagt til test for median.
=> Tell dokumenter når saken har en "avsluttet"-status.

src/main/resources/application.yml
TODO: Lage grense for størrelse på opplastet fil i løsningen.
=> Fikser feil i henting av dokument fra SAF.

src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingDistribusjonService.kt, src/test/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingDistribusjonServiceTest.kt
La til test for å verifisere at riktig funksjoner blir kalt.
=> Henter ut det oppdaterte vedtaket etter lagBrevmottakere-kallet.

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingEditableFieldsInput.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingEditableFieldsFacade.kt
Gjør om til tom streng på veien ut.
=> Tolker tom streng i internVurdering som null. 

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/VedleggEditedView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/VedleggView.kt
Co-authored-by: Andreas Jonsson <andreas.jonsson@nav.no>
=> La til file i VedleggEditedView. La til Opplastet i VedleggView.

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingListController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingListMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingerQueryParamsMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingListView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/PersonSoekInput.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/PersonSokInput.kt, src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt, src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt, src/test/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingListMapperTest.kt
Eget endepunkt som bruker POST for å skjerme fnr fra loggene.
Mangler tester, de kommer senere, men ønsket at SA skulle få se hvordan APIet blir seende ut. Dere andre kan gjerne se om koden ser grei ut også. :)
=> Lagt til muligheten til å søke med fnr gjennom et person. 

src/main/kotlin/no/nav/klage/oppgave/service/TilgangService.kt, src/main/kotlin/no/nav/klage/oppgave/service/VedtakService.kt, src/test/kotlin/no/nav/klage/oppgave/service/TilgangServiceTest.kt
og ikke gjøre andre endringer i klagebehandlingen.
=> Medunderskriver skal kun ha lov til å godkjenne vedtak

src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/kotlin/no/nav/klage/oppgave/service/VedtakService.kt, src/test/kotlin/no/nav/klage/oppgave/service/KlagebehandlingServiceTest.kt
=> Ignore general checkSkrivetilgang(), and do specific check

src/main/kotlin/no/nav/klage/oppgave/service/IndexService.kt
.. da vi ser at den også feiler innimellom
=> Flyttet mappingen inn i try-catch blokka,

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingerSearchCriteriaMapper.kt, src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt, src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt
Er ment som en forberedelse til navnesøk og ektefellesøk..
=> Lagt til støtte for å kunne søke med flere fnr mot ES. 

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingListController.kt
hvis ingenting er sendt med fra frontend
=> Lagt på en grunnfiltrering på lovlige temaer for saksbehandler

src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt, src/main/kotlin/no/nav/klage/oppgave/service/TilgangService.kt, src/test/kotlin/no/nav/klage/oppgave/service/FortroligElasticsearchServiceTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/TilgangServiceTest.kt
Har endret både i visning av én person/klagebehandling, og i søk mot ES. Har skrevet tester for å verifisere begge usecase.
Er litt komplisert, setter pris på god review! :)
=> Endre tilgangsregler for kode6, 7 og egne ansatte

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingDokumentController.kt, src/main/kotlin/no/nav/klage/oppgave/service/DokumentService.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
=> Returner unike journalposter.

src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingAvslutningService.kt, src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingDistribusjonService.kt
…så status skal bli riktig i ES
=> Publiserer event også når vi avslutter klagebehandling, 

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphClient.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klager.kt, src/main/kotlin/no/nav/klage/oppgave/service/FileApiService.kt
når frontend har tatt dem i bruk kan vi fjerne alle de utflata feltene..
=> Lagt til objekter for klager og sakenGjelder i KlagebehandlingDetaljerView

src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt
Endret så oppgaver man er medunderskriver på bare blir inkludert når medunderskriverflyt er i riktig fase
=> Fiks for medunderskriver i ES

src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingDetaljerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/filter/TimingFilter.kt, src/main/kotlin/no/nav/klage/oppgave/domain/elasticsearch/EsKlagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Prosessfullmektig.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/SendKlageEndretToKafkaEventListener.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingEndretKafkaProducer.kt, src/main/kotlin/no/nav/klage/oppgave/service/StatistikkTilDVHKafkaProducer.kt, src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingAvslutningService.kt, src/main/kotlin/no/nav/klage/oppgave/service/mapper/EsKlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/service/mapper/KlagebehandlingSkjemaV1Mapper.kt, src/main/resources/application-dev-gcp.yml, src/main/resources/application-prod-gcp.yml, src/main/resources/elasticsearch/mapping.json
Mapper til KlagebehandlingSkjemaV1, som er en klasse som representerer "kontrakten" i topicen, og som må lese ut og mappes til EsKlagebehandling på andre siden for å indekseres.
=> Skriver oppdaterte klagebehandlinger til Kafka. 

src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KodeverkResponse.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/KlagebehandlingAggregatFunctions.kt, src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Hjemmel.kt, src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Ytelse.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/resources/db/migration/V30__Add_ytelse.sql
Co-authored-by: Hågen Hasle <hagen.hasle@nav.no>
Co-authored-by: Andreas Jonsson <andreas.jonsson@nav.no>
=> Expanded model, removed unused methods.

src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Ytelse.kt, src/main/kotlin/no/nav/klage/oppgave/service/mapper/KlagebehandlingSkjemaV1Mapper.kt
Denne kan ikke merges før kabal-search er klar for ytelse. 
Krever også at man gjør admin-operasjonen hvor man syncer db med kafka, så må følges hele veien ut i prod.
=> Utvider KlagebehandlingSkjemaV1 med ytelse

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingVedtakController.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/KodeverkResponse.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/OversendtKlage.kt, src/main/kotlin/no/nav/klage/oppgave/clients/kaka/KakaApiGateway.kt, src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/KlagebehandlingAggregatFunctions.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/MottakHjemmel.kt, src/main/kotlin/no/nav/klage/oppgave/domain/klage/Vedtak.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/main/kotlin/no/nav/klage/oppgave/service/VedtakService.kt, src/test/kotlin/no/nav/klage/oppgave/api/KlagebehandlingControllerTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/KlagebehandlingRepositoryTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/MeldingRepositoryTest.kt, src/test/kotlin/no/nav/klage/oppgave/repositories/MottakRepositoryTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/KlagebehandlingServiceTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/TilgangServiceTest.kt, src/test/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingDistribusjonServiceTest.kt
Filters hjemmel values sent to kaka, to avoid errors.
=> New kodeverk version.

src/main/kotlin/no/nav/klage/oppgave/api/controller/SaksbehandlerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/Medunderskriver.kt, src/main/kotlin/no/nav/klage/oppgave/service/SaksbehandlerService.kt
Når FE har endret fra ident -> navIdent kan vi erstatte Medunderskriver med SaksbehandlerView
=> Skritt på vegen for å erstatte Medunderskriver med SaksbehandlerView

src/main/kotlin/no/nav/klage/oppgave/domain/klage/MottakDokument.kt
så førsteinstans skal kunne sende over flere dokumenter
(Jeg vet at ikke K9 bruker dette pt, men jeg håper de kan begynne med det. :) )
=> Utvidet MottakDokumentType i mottaket, 

docs/schema/behandling-events.json, src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingAvslutningService.kt
Kafka-objektet får da egen ID, ikke samme som eventene
=> Publiserer vedtakFattet og behandlingEvent samtidig. 

.github/workflows/manual-deploy-kafka-aiven.yaml
Endret til o bruke matrix for bedre oversikt.
=> Oppdatert kafka-deploy-workflow

src/main/kotlin/no/nav/klage/dokument/api/controller/SmartEditorController.kt, src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt
=> Verify that saksbehandler has access to modify smartEditor document 

build.gradle.kts, src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt
Validate utfall based on type.
=> Use kodeverk with AnkeITrygderetten.

src/main/kotlin/no/nav/klage/oppgave/domain/klage/Delbehandling.kt, src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt, src/main/resources/db/migration/V56__Migrate_utfall.sql
=> Migrate utfall and put back validation

src/main/kotlin/no/nav/klage/oppgave/domain/klage/Delbehandling.kt, src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt
Remove hjemmel validation for retur.
Co-authored-by: Andreas Jonsson <andreas.jonsson@nav.no>
=> Remove kvalitetsvurdering validation for retur and ugunst.

src/main/kotlin/no/nav/klage/dokument/domain/dokumenterunderarbeid/DokumentUnderArbeid.kt, src/main/kotlin/no/nav/klage/dokument/domain/dokumenterunderarbeid/DokumentUnderArbeidJournalpostId.kt, src/main/kotlin/no/nav/klage/dokument/service/DokumentUnderArbeidService.kt, src/main/kotlin/no/nav/klage/oppgave/clients/kabaldocument/model/response/DokumentEnhetFullfoerOutput.kt, src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/BehandlingAvslutningService.kt, src/main/resources/db/migration/V57__Add_journalposter.sql, src/test/kotlin/no/nav/klage/oppgave/service/distribusjon/BehandlingAvslutningServiceTest.kt
=> Lagrer alle journalposter på dokumentUnderArbeid.

src/main/kotlin/no/nav/klage/dokument/api/controller/DokumenterUnderArbeidController.kt, src/main/kotlin/no/nav/klage/dokument/clients/kabaljsontopdf/KabalJsonToPdfClient.kt, src/main/kotlin/no/nav/klage/dokument/clients/kabaljsontopdf/domain/DocumentValidationResponse.kt, src/main/kotlin/no/nav/klage/dokument/exceptions/DokumentExceptions.kt, src/main/kotlin/no/nav/klage/dokument/service/DokumentUnderArbeidService.kt, src/main/kotlin/no/nav/klage/oppgave/config/problem/ProblemHandlingControllerAdvice.kt, src/test/kotlin/no/nav/klage/oppgave/LayeredArchitectureTest.kt
=> New validation response for documents

src/main/kotlin/no/nav/klage/oppgave/domain/kafka/StatistikkTilDVH.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHService.kt, src/main/kotlin/no/nav/klage/oppgave/service/AdminService.kt
=> Patch events to DVH. Set TR0000 as enhet when results are from TR.

deploy/nais.yaml, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingAssignmentController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingMedunderskriverController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/BehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/MedunderskriverFlytResponse.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/MedunderskriverInfoView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/SakenGjelderWrapped.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/SaksbehandlerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/TildelingEditedView.kt, src/main/kotlin/no/nav/klage/oppgave/clients/kabalinnstillinger/KabalInnstillingerClient.kt, src/main/kotlin/no/nav/klage/oppgave/clients/kabalinnstillinger/model/RequestResponse.kt, src/main/kotlin/no/nav/klage/oppgave/config/KabalInnstillingerClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/config/KabalInstillingerClientConfiguration.kt, src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt, src/main/kotlin/no/nav/klage/oppgave/service/KabalInnstillingerService.kt, src/main/kotlin/no/nav/klage/oppgave/util/TokenUtil.kt, src/main/resources/application.yml, src/test/kotlin/no/nav/klage/oppgave/api/BehandlingMedunderskriverControllerTest.kt, src/test/kotlin/no/nav/klage/oppgave/api/mapper/BehandlingMapperTest.kt
=> New response for tildeling.

src/main/kotlin/no/nav/klage/dokument/api/controller/DokumenterUnderArbeidController.kt, src/main/kotlin/no/nav/klage/dokument/api/view/DokumentUnderArbeidInput.kt, src/main/kotlin/no/nav/klage/oppgave/clients/kabaldocument/KabalDocumentMapper.kt, src/test/kotlin/no/nav/klage/oppgave/clients/kabaldocument/KabalDocumentMapperTest.kt
Use SAKEN_GJELDER as brevmottaker for DokumentType.NOTAT.
=> Allow null input in /ferdigstill. 

src/main/kotlin/no/nav/klage/oppgave/api/controller/KabinApiController.kt, src/main/kotlin/no/nav/klage/oppgave/clients/pdl/PdlFacade.kt, src/main/kotlin/no/nav/klage/oppgave/exceptions/Exceptions.kt, src/main/kotlin/no/nav/klage/oppgave/service/FullmektigSearchService.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
Allows severe errors (ie PDL down) to pass through to clients.
=> Better handling of PDL errors.

src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingDetaljerController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingDokumentController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingMedunderskriverController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingMeldingController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingVedtakController.kt, src/main/kotlin/no/nav/klage/oppgave/api/filter/TimingFilter.kt, src/test/kotlin/no/nav/klage/oppgave/api/BehandlingMedunderskriverControllerTest.kt
Add parallell /behandlinger path to all /klagebehandlinger paths.
=> Remove unused arkivertedokumenter pdf end point.

src/main/kotlin/no/nav/klage/oppgave/api/controller/KabinApiController.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/kabin/KabinRequest.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/kabin/KabinResponse.kt, src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt, src/test/kotlin/no/nav/klage/oppgave/service/distribusjon/BehandlingAvslutningServiceTest.kt
Accept saksbehandlerIdent as input.
=> Include previous saksbehandler in klagemulighet.

src/main/kotlin/no/nav/klage/dokument/api/controller/DokumenterUnderArbeidController.kt, src/main/kotlin/no/nav/klage/dokument/api/mapper/DokumentMapper.kt, src/main/kotlin/no/nav/klage/dokument/api/view/DokumentUnderArbeidInput.kt, src/main/kotlin/no/nav/klage/dokument/api/view/DokumentUnderArbeidView.kt, src/main/kotlin/no/nav/klage/dokument/repositories/DokumentUnderArbeidRepository.kt, src/main/kotlin/no/nav/klage/dokument/service/DokumentUnderArbeidService.kt
Adds end point for setting parent of multiple documents.
=> Fix duplicate bug for journalfoert dokument when moving vedlegg.

src/main/kotlin/no/nav/klage/oppgave/api/controller/BehandlingDokumentController.kt, src/main/kotlin/no/nav/klage/oppgave/api/controller/JournalpostController.kt, src/main/kotlin/no/nav/klage/oppgave/api/mapper/BehandlingMapper.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/BehandlingDetaljerView.kt, src/main/kotlin/no/nav/klage/oppgave/api/view/DokumentView.kt, src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt, src/main/kotlin/no/nav/klage/oppgave/service/DokumentService.kt
Include relevant document list in details.
Include lists of relevant sort values in arkivertedokumenter response.
=> Remove unused controller.

deploy/dev.yaml, deploy/prod.yaml
Ser ut som om konfigen ble satt opp litt feil
=> bytte access -> cluster for etterlatte

src/main/kotlin/db/migration/V120__dvh_set_TR_enhet.kt, src/main/kotlin/db/migration/V121__dvh_utfall_rename.kt, src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHService.kt, src/main/resources/db/migration/V122__delete_dvh_stat.sql
Migrate utfall names in dvh stats messages.
Delete single dvh stat message.
=> Add missing Trygderett enhet to dvh stats messages.

src/main/resources/db/migration/V127__feilregistrer.sql
=> Feilregistrer behandlinger

src/main/kotlin/no/nav/klage/oppgave/api/controller/AdminController.kt, src/main/kotlin/no/nav/klage/oppgave/service/AdminService.kt, src/main/kotlin/no/nav/klage/oppgave/service/SaksbehandlerService.kt
Method for getting cached version of navIdents for roles.
=> Log all inaccessible behandlinger in Kabal.

deploy/dev.yaml, deploy/prod.yaml
we're not planning to use the prod-gcp endpoint right now, but we will soon(tm)!!
=> give access to dp-saksbehandling
