navikt/kabal-api

- src/main/kotlin/no/nav/klage/oppgave/api/FeatureToggleController.kt
Lagt på en try-catch rundt henting av ident, returnerer UINNLOGGET hvis det ikke er en innlogget bruker. Jeg er ikke 100% sikker på denne her, men antar at det gir mening å kunne ha toggles også kun per miljø, og da uten å måtte ha en innlogget bruker. Så jeg tror det er lurt. :)
> Fix så henting av featuretoggles også fungerer når bruker ikke er innlogget

- src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt
Har endret OppgaveClient så vi henter ut en og en page fra Oppgaver til alle oppgavene som er tilgjengelige er hentet ut, slår det så sammen og returnerer det videre.
> Returnere alle tilgjengelige oppgaver, ikke bare en page

- src/main/kotlin/no/nav/klage/oppgave/api/OppgaveController.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/gosys/Oppgave.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/view/OppgaveView.kt
- src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt
- src/test/kotlin/no/nav/klage/oppgave/service/OppgaveServiceTest.kt
Her har jeg gjort en litt klassisk Hågen-tabbe, og tatt litt for mye med inn i PRen.. Det er egentlig tre ting her, jeg har gjort om hjemmel fra å være List<String> til å være String, jeg har refaktorert litt eksisterende kode, og jeg har lagt til kode for å assigne en saksbehandler til en oppgave.
Jeg hadde tenkt til å se om jeg kunne dele det opp i tre PRer i stedet for en, men så så jeg at frontend-endringen som matcher hjemmel-endringen allerede var dyttet ut, så da tenkte jeg at det var greit å få det ut..
> Assign saksbehandler til Oppgave

- src/main/kotlin/no/nav/klage/oppgave/config/problem/ProblemHandlingControllerAdvice.kt
- src/test/kotlin/no/nav/klage/oppgave/api/ProblemHandlingTest.kt
…så de mappes slik at vi returnerer samme statuskode til frontend som klienten vår gjorde til oss
> Lagt til håndtering av WebClientResponseException 

- src/main/kotlin/no/nav/klage/oppgave/clients/OppgaveClient.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/OppgaverSearchCriteria.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/gosys/Oppgave.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/view/OppgaveView.kt
- src/main/kotlin/no/nav/klage/oppgave/service/OppgaveService.kt
- src/test/kotlin/no/nav/klage/oppgave/service/OppgaveServiceTest.kt
Alltid bruk enhetsnr ved søk. Søk inkluderer klage/anke hvis inget annet angitt.
På sikt må vi finne ut om vi kan håndtere disse kodeverkstrengene litt penere.
Ikke merge før url til axsys i api-gw er lagt inn.
> Always include enhetsnr in queries.

- build.gradle.kts
- src/main/resources/db/migration/V1__Create_oppgave_copy.sql
- src/test/kotlin/no/nav/klage/oppgave/db/FlywayMigrationTest.kt
- src/test/resources/application-test.yml
Lagt til flyway-migreringer for Oppgave-kopi-skjema, samt test av at det kjører som det skal.
Skjemaene er basert på det Oppgave har, som ligger her: 
https://github.com/navikt/oppgave/tree/master/src/main/resources/database/flyway/migrations/common
Men tilpasset fordi vi mottar oppgavene som Kafka-records/REST (https://github.com/navikt/oppgave/blob/master/src/main/java/no/nav/oppgave/infrastruktur/kafka/OppgaveKafkaRecord.java), og ikke har det samme forholdet til alle IDer og sånt. Ei heller trenger alle tabellene. Så jeg har tilpasset så godt jeg kan, men mulig vi må endre litt når vi begynner å lagre dataene.
> Lagt til flyway-migreringer for Oppgave-kopi-skjema

- build.gradle.kts
- deploy/nais.yaml
…som ikke lenger skal være nødvendig. Har nå tatt bort webproxy-biten i nais.yaml også, som vi ikke skal trenge i gcp og som kan skapt trøbbel for Azure-integrasjonen
> Nytt forsøk på å fjerne security dep 

- src/main/kotlin/no/nav/klage/oppgave/api/internal/OffsetDateTimeToLocalDateTimeDeserializer.kt
- src/main/kotlin/no/nav/klage/oppgave/api/internal/OppgaveKopiAPIModel.kt
They make a LocalDateTime into an OffsetDateTime when serializing to JSON (and back when deserializing). The offset part can be ignored as we only care about local time.
> Use same strategy as oppgave to parse datetime

- src/main/kotlin/no/nav/klage/oppgave/api/DokumentController.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/DokumentMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/DokumentView.kt
- src/main/kotlin/no/nav/klage/oppgave/repositories/SaksdokumentRepository.kt
- src/main/kotlin/no/nav/klage/oppgave/service/DokumentService.kt
Samt lagt til et endepunkt for å returnere en skinny liste over tilkoblete journalposter.
Så nå kan Sven Anders vurdere hvilken approach han liker best.. 
Jeg innser at REST-biten av dette ikke henger helt på greip nå, iom at jeg tilbyr GET på både /klagebehandlinger/{behandlingsid}/dokumentreferanser og /klagebehandlinger/{behandlingsid}/dokumenter, men POST kun på /klagebehandlinger/{behandlingsid}/dokumenter og DELETE kun på /klagebehandlinger/{behandlingsid}/dokumenter. Greia var at jeg ville gjerne ha en annen response fra det "skinny" endepunktet, og da måtte jeg lage det på en egen URL. Men vi får se hva vi lander på, og så kan jeg endre og gjøre det mer harmonisert..
> Lagt til endepunkt for å slette en kobling mellom en klagebehandling og en journalpost

- src/main/kotlin/no/nav/klage/oppgave/api/mapper/OppgaveMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/OppgaverQueryParamsMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/OppgaveView.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/OppgaverQueryParams.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/OppgaverSearchCriteria.kt
- src/main/kotlin/no/nav/klage/oppgave/repositories/ElasticsearchRepository.kt
- src/test/kotlin/no/nav/klage/oppgave/clients/OppgaveClientTest.kt
og tilsvarende i OppgaverQueryParams og nedover i ES-søket så man kan velge å sortere på mottattDato i stedet for frist
> Utvider OppgaveView med mottattDato, 

- src/main/kotlin/no/nav/klage/oppgave/api/KlagebehandlingFacade.kt
- src/main/kotlin/no/nav/klage/oppgave/api/KlagebehandlingListController.kt
- src/main/kotlin/no/nav/klage/oppgave/api/OppgaveFacade.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingerQueryParamsMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/OppgaveMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingListView.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingView.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingerQueryParams.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/Saksbehandlertildeling.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/gosys/OppgaveClient.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/pdl/Person.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/pdl/graphql/HentPersonMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt
- src/main/kotlin/no/nav/klage/oppgave/repositories/ElasticsearchRepository.kt
- src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/OppgaveStatistikkService.kt
- src/test/kotlin/no/nav/klage/oppgave/clients/OppgaveClientTest.kt
- src/test/kotlin/no/nav/klage/oppgave/service/ElasticsearchRepositoryTest.kt
Lagt til KlagebehandlingListController som en erstatning for OppgaveController. Den bruker IDen til enums for sakstype og tema, ikke navnet. Så frontend må slå opp kodene fra KodeverkController for å kunne vise navnet. Har også renamet en del fra oppgave til klagebehandling nedover i koden.
Har også endret så vi ikke stapper inn "mangler" der vi ikke finner navn eller fnr, men i stedet har blanke felt. Hva som vises i gui bør ikke bestemmes i backend.
> Harmonisere kode

- src/main/kotlin/no/nav/klage/oppgave/api/KlagebehandlingFacade.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/klage/Klagebehandling.kt
- src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
- src/test/kotlin/no/nav/klage/oppgave/repositories/KlagebehandlingRepositoryTest.kt
Gjort hjemler om til et set, og gjort hjemler og saksdokumenter eager fetched. Slipper da lazyloading feil på dem. Kvalitetsvurdering brukes bare i sidene for kvalitetsvurdering, så jeg initialiserer dem inni transaksjonen før de sendes ut
> Forslag til håndtering av lazy loading i JPA

- src/main/kotlin/no/nav/klage/oppgave/api/controller/UnprotectedTestOversendelseController.kt
en ordinær, en for egenAnsatt, en for kode 6, en for kode 7 og en for kode 19. Testpersonene er laget i Dolly på forhånd.
> Lagt til en controller som genererer fem test-klager

- src/main/kotlin/no/nav/klage/oppgave/api/controller/AdminController.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingerQueryParamsMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt
- src/main/kotlin/no/nav/klage/oppgave/repositories/ElasticsearchRepository.kt
- src/main/kotlin/no/nav/klage/oppgave/service/AdminService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/IndexService.kt
- src/main/resources/elasticsearch/mapping.json
- src/test/kotlin/no/nav/klage/oppgave/service/CreateIndexFromEsOppgaveTest.kt
Lagt til (midlertidig) kode for å parse hjemler fra gui om til int. Gjort så vi sletter og gjenskaper indexen når vi nuker den, ikke bare sletter alle dokumentene i den. Oppdatert mappingen med riktig definisjon for hjemler
> Es admin og sok tilpasning

- build.gradle.kts
- src/main/kotlin/no/nav/klage/oppgave/config/SchedulingConfiguration.kt
- src/main/kotlin/no/nav/klage/oppgave/service/AdminService.kt
- src/main/resources/db/migration/V2__Create_shedlock.sql
Dette kunne vært håndtert på en rekke andre måter også, men jeg tenkte at siden vi allerede bruker Postgres, så gjør det ikke noe å ha en dependency til det også i dette tilfelle, og shedlock har jeg erfaring med fra før, så det var kjapt å få på plass.
> Lagt til støtte for shedlock så scheduled tasks bare skal kjøre på en pod

- src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingListView.kt
I frontend er det antatt at `erMedunderskriver` er `string` eller `null`.
I backend er `erMedunderskriver` `boolean` eller `null`.
Jeg forslår at vi renskriver dette til at `erMedunderskriver` er `boolean` og at vi utvider med en ny egenskap som indikerer om det er en medunderskriver (`harMedunderskriver`), som også er `boolean`.
> Utvid og tydeliggjør er/harMedunderskriver

- src/main/kotlin/no/nav/klage/oppgave/config/FunksjonelleGaugesConfiguration.kt
Jeg håper at denne fiksen kan gjøre at noen av feilene vi ser i loggene blir borte, spesifikt disse:
Failed to apply the value function for the gauge 'funksjonell.sendttilmedunderskriver'.
failed to send metrics to influx
Men jeg må innrømme at jeg synes det er rart at ikke Spring/Micrometer gjør dette allerede..
> Et forsøk på å bli kvitt feil i loggene ved shutdown

- src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingDokumentController.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/saf/graphql/HentDokumentoversiktBrukerRequest.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/saf/graphql/SafGraphQlClient.kt
- src/main/kotlin/no/nav/klage/oppgave/service/DokumentService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/KlagebehandlingService.kt
- src/main/resources/saf/hentDokumentoversiktBruker.graphql
- src/test/kotlin/no/nav/klage/oppgave/clients/SafDokumentoversiktBrukerTest.kt
Har ikke lagt det til i apiet i KlagebehandlingDokumentController ennå, tenkte det kunne være en egen endring
Denne endringen trengs for å få til https://trello.com/c/WjuM4mgN/270-kunne-filtrere-p%C3%A5-tema-i-dokumentlista-i-kabal-saksbehandling.
Jeg har prøvd å titte på hvordan det er gjort i Lovme da jeg gjorde denne endringen. (Ref https://github.com/navikt/medlemskap-oppslag/blob/master/saf-client/src/main/resources/saf/dokumenter.graphql)
> Lagt til støtte for filtrering på tema i saf-kallet hentDokumentoversiktBrukerQuery

- src/main/kotlin/no/nav/klage/oppgave/api/controller/KlagebehandlingDetaljerController.kt
- src/main/kotlin/no/nav/klage/oppgave/api/mapper/KlagebehandlingListMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/KlagebehandlingListView.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/KodeverkResponse.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/pdl/Person.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/pdl/graphql/HentPersonMapper.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/KlagebehandlingerSearchCriteria.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/SivilstandType.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Tema.kt
- src/main/kotlin/no/nav/klage/oppgave/service/ElasticsearchService.kt
- src/test/kotlin/no/nav/klage/oppgave/service/EktefelleElasticsearchServiceTest.kt
Lagt til et endepunkt for å vise relaterte klager.
Lagt til støtte for å kunne søke på en ekstra kombinasjon av fnr og tema i ES, så man kan vise klager for ektefelle og partner, men med andre tema enn det vanlige søket.
> Relaterte klager

- src/main/kotlin/no/nav/klage/oppgave/service/VedtakService.kt
- src/test/kotlin/no/nav/klage/oppgave/api/KlagebehandlingDetaljerControllerTest.kt
- src/test/kotlin/no/nav/klage/oppgave/service/VedtakServiceTest.kt
for å sikre at endring på medunderskriver-flyten ikke påvirker denne.
Sjekken på mellomlagerid i VedtakService slapp for mye igjennom, det er nå krav om at vedtak fins i mellomlageret for å avslutte klagebehandlingen.
> Legger til tester for eksisterende fullfør-flyt, 

- src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHEventListener.kt
- src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHService.kt
Litt av greia med outbox-patternet (store-and-forward), er at man ikke trenger distribuerte transaksjoner. Det er enklere (mulig!) å holde i sync de lokale endringene du selv gjør med meldingen du skal sende ut på Kafka, fordi man lagrer meldingen i outboxen i samme transaksjon som man lagrer det andre man har gjort. 
Men det ser jeg at ikke er tilfelle for oss. Koden vår i StatistikkTilDVHEventListener er annotert til å kjøre async og *etter* at hovedtransaksjonen er commited. Dette ga jo mening før, men kanskje ikke nå lenger? Så her er en PR for å endre det.
Iom at dette nå da vil kalles hver eneste gang vi oppdaterer en klagebehandling, så flyttet jeg bruken av if (shouldSendStats(...)) øverste i process-metoden, så vi slipper å hente Mottak unødvendig.
> Endringer i StatistikkTilDVHEventListener

- src/main/kotlin/no/nav/klage/oppgave/api/controller/SaksbehandlerController.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/Medunderskriver.kt
- src/main/kotlin/no/nav/klage/oppgave/api/view/Saksbehandlertildeling.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/kodeverk/Ytelse.kt
- src/main/kotlin/no/nav/klage/oppgave/service/SaksbehandlerService.kt
Jeg har ikke fjernet endepunktet for tema, så det er fremdeles operativt.
Det nye endepunktet for ytelse har fått en litt annen URL, den ser nå ut som dette:
`/medunderskrivere/ytelser/{ytelse}/enheter/{enhet}/ansatte/{navIdent}`
Den gamle med tema var
`/ansatte/{navIdent}/medunderskrivere/{tema}`
Tanken er at vi kan trenge enhet i tillegg til ytelse, ref diskusjon på slack:
https://nav-it.slack.com/archives/C02K9CB309J/p1637675163034000
(og tilhørende poster over og under)
Jeg har ikke laget koden for å sortere medunderskriverne i riktig rekkefølge basert på enhet, det får komme senere. Men med den nye URLen så blir det iallefall mulig.
Vi lagrer forøvrig ikke enhetId for medunderskriver ser jeg, bare ident. Så sånn sett så er det egentlig ingen som vet hvilken enhet medunderskriver …
> Lagt til endepunkt for å slå opp medunderskrivere basert på ytelse

- build.gradle.kts
- src/main/kotlin/no/nav/klage/oppgave/clients/azure/DefaultAzureGateway.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphClient.kt
- src/main/kotlin/no/nav/klage/oppgave/clients/azure/MicrosoftGraphResponse.kt
- src/main/kotlin/no/nav/klage/oppgave/config/problem/ProblemHandlingControllerAdvice.kt
- src/main/kotlin/no/nav/klage/oppgave/domain/saksbehandler/SaksbehandlerPersonligInfo.kt
- src/main/kotlin/no/nav/klage/oppgave/exceptions/Exceptions.kt
(Koden er testet i dev, og den fungerer. Men testbrukerne våre tilhører et kontor vi ikke har (NAV IKT DRIFT), så vi må få endret på det før dette kan merges.
Punkt til diskusjon: Jeg bruker her i kabal ikke kode-enumen vår, men domeneklassen vi hadde fra før og bruker andre steder. Jeg tenker at skal vi endre til enumen så bør vi gjøre det over hele fjøla, ikke bare akkurat her.
> Lagt til kode for å hente ut enheten saksbehandler er ansatt i fra Azure

- src/main/resources/application.yml
- src/test/kotlin/no/nav/klage/oppgave/db/TestPostgresqlContainer.kt
Det hender jeg får connection problemer i testene (mot Postgres) etter overgangen til Colima. Disse to endringene er ting andre i Nav har gjort for å bli kvitt det problemet.
> Små tweaks for å forhindre Colima-problemer

- src/main/kotlin/no/nav/klage/dokument/api/controller/DokumenterUnderArbeidController.kt
Alt som eksponeres her er UUID til dokumenter som blir ferdigstilte for en gitt behandling-UUID.
> No need for protection for this sse-endpoint

- src/main/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHService.kt
- src/main/resources/db/migration/V67__Remove_it01_to_dvh:in_kafka_events.sql
- src/main/resources/db/migration/V67__Remove_it01_to_dvh_in_kafka_events.sql
- src/test/kotlin/no/nav/klage/oppgave/eventlisteners/StatistikkTilDVHServiceTest.kt
Added tests for shouldSendStats.
Delete wrongly produced kafka events.
> Avoid dvh stats when dealing with Fagsystem IT01.

- build.gradle.kts
We get some errors in async/sse operations from token-support. It seems to work though, but will revert the changes for now.
> Downgrade Spring Boot

- src/main/kotlin/no/nav/klage/dokument/service/DokumentUnderArbeidService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/distribusjon/KlagebehandlingSchedulerService.kt
Reverse list when handling completion, to avoid holdup due to missing access to KA-rutinen/Infotrygd.
> Send svarbrev to klager if it differs from saken gjelder.

- src/main/kotlin/no/nav/klage/dokument/service/DokumentUnderArbeidService.kt
- src/main/kotlin/no/nav/klage/dokument/service/PreviewService.kt
- src/main/kotlin/no/nav/klage/oppgave/api/controller/SearchController.kt
- src/main/kotlin/no/nav/klage/oppgave/service/AutomaticSvarbrevService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/BehandlingService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/ForlengetBehandlingstidDraftService.kt
- src/main/kotlin/no/nav/klage/oppgave/service/PartSearchService.kt
`skipAccessControl` renamed to `systemUserContext`.
> Only check saksbehandler access if needed.
